### ISSUE TITLE
Available edit options won't let you edit.

### ISSUE THREAD

**Issue by stanholzendorf** [jordansavant/ncmysql#1]
Modes "key, "describe" and "show-create" all have the option edit available to them inside the results frame, if selected however the program will return the error "No primary key could  be determined for this fields table".

**Comment by jordansavant** [comment]
Good catch with this. I have updated the program to detect if a field is properly editable by ncmysql before presenting the option for editing. This should only show the edit capability if:

1. there is a MYSQL Field connected to the focused cell
2. there is a valid database connected to the field (hard set to exclude mysql, information_db, and innodb currently)
3. the table can be determined for the field
4. a primary key can be determined (this is related to another issue where we cannot use the cell editor to modify contents of tables that have more than one primary key) this is in another issue already
