### ISSUE TITLE
Table updates issue.

### ISSUE THREAD

**Issue by stanholzendorf** [jordansavant/ncmysql#2]
When updating a table, for example table name, the application its table/selection frame does not refresh after successfully running the query. This leads to an error when trying to view the table, since the application looks for a non-existing table. One has to exit   the application to see the changes.

**Comment by jordansavant** [comment]
I am going to refresh the table listing on each execution of a query to ensure its up to date

**Comment by jordansavant** [comment]
Table refresh has been applied to the primary execute function for a the SQL written in the query editor.
So we should see the table list refresh when we RENAME, CREATE or DROP a table.
