### ISSUE TITLE
Query feedback.

### ISSUE THREAD

**Issue by stanholzendorf** [jordansavant/ncmysql#3]
I may be beneficial if there was some type of visual feedback of a successful query. Not so much for the Data in the table but for queries that affect the table itself. Renaming a table for example.

**Comment by jordansavant** [comment]
Ahh sounds good. I bet in this scenario there is no "Affected Rows" so its not printing that out. I will test it and get some sort of execution response in there.

**Comment by jordansavant** [comment]
This has been resolved with this: https://github.com/jordansavant/ncmysql/issues/2
